<?php

return [
    'from' => 'production',
    'to' => 'staging',
    'tables' => [
        // 'dms_ap_supplier',
        // 'dms_ar_customer',
        // 'dms_ar_customercategory',
        // 'dms_ar_customercategorytype',
        // 'dms_ar_customerhierarchy',
        // 'dms_ar_customerrouteinfo',
        // 'dms_ar_doccustomer',
        // 'dms_ar_paymentterm',
        // 'dms_ar_paymenttype',
        // 'dms_ar_pricesegment',
        // 'dms_fin_account',
        // 'dms_fin_subaccount',
        // 'dms_inv_carrier',
        // 'dms_inv_product',
        // 'dms_inv_productcategory',
        // 'dms_inv_productcategorytype',
        // 'dms_inv_uom',
        // 'dms_inv_vehicle',
        // 'dms_inv_vehicletype',
        // 'dms_inv_warehouse',
        // 'dms_sd_pricecatalog',
        // 'dms_sd_route',
        'dms_inv_docstockinbranch',        
        'dms_inv_docstockindistribution',
        'dms_inv_docstockindistributionitem',
        'dms_inv_docstockinsupplier',
        'dms_inv_docstockinsupplieritem',
        'dms_inv_docstockinsupplierotm',
        'dms_inv_docstockinsupplierotmitem',
        'dms_inv_docstockoutbranch',
        'dms_inv_docstockoutbranchitem',
        'dms_inv_docstockoutdistribution',
        'dms_inv_docstockoutdistributionitem',
        'dms_inv_docstockoutdistributionpr',
        'dms_inv_docstockoutdistributionpritem',
        'dms_inv_docstockoutsupplier',
        'dms_inv_docstockoutsupplieritem',
        'dms_pi_employeedistribution',
        'dms_sd_calendarbranch',
        'dms_sd_docdo',
        'dms_sd_docdocorrection',
        'dms_sd_docdocorrectionitem',
        'dms_sd_docdoinvoice',
        'dms_sd_docdoitem',
        'dms_sd_docdoitemprice',
        'dms_sd_docdoitempromo',
        'dms_sd_docdoitemreason',
    ],
    'conditions' => ['dms_ap_supplier' => 'dtmLastUpdated',
        'dms_ar_customer' => 'dtmLastUpdated',
        'dms_ar_customercategory' => 'dtmLastUpdated',
        'dms_ar_customercategorytype' => 'dtmLastUpdated',
        'dms_ar_customerhierarchy' => 'dtmLastUpdated',
        'dms_ar_customerrouteinfo' => 'dtmLastUpdated',
        'dms_ar_doccustomer' => 'dtmLastUpdated',
        'dms_ar_paymentterm' => 'dtmLastUpdated',
        'dms_ar_paymenttype' => 'dtmLastUpdated',
        'dms_ar_pricesegment' => 'dtmLastUpdated',
        'dms_fin_account' => 'dtmLastUpdated',
        'dms_fin_subaccount' => 'dtmLastUpdated',
        'dms_inv_carrier' => 'dtmLastUpdated',
        'dms_inv_product' => 'dtmLastUpdated',
        'dms_inv_productcategory' => 'dtmLastUpdated',
        'dms_inv_productcategorytype' => 'dtmLastUpdated',
        'dms_inv_uom' => 'dtmLastUpdated',
        'dms_inv_vehicle' => 'dtmLastUpdated',
        'dms_inv_vehicletype' => 'dtmLastUpdated',
        'dms_inv_warehouse' => 'dtmLastUpdated',
        'dms_sd_pricecatalog' => 'dtmLastUpdated',
        'dms_sd_route' => 'dtmLastUpdated',
        'dms_inv_docstockinbranch' => 'dtmLastUpdated',
        'dms_inv_docstockinbranchitem' => 'dtmLastUpdated',
        'dms_inv_docstockindistribution' => 'dtmLastUpdated',
        // 'dms_inv_docstockindistributionitem' => 'dtmLastUpdated',
        'dms_inv_docstockinsupplier' => 'dtmLastUpdated',
        'dms_inv_docstockinsupplieritem' => 'dtmLastUpdated',
        'dms_inv_docstockinsupplierotm' => 'dtmLastUpdated',
        'dms_inv_docstockinsupplierotmitem' => 'dtmLastUpdated',
        'dms_inv_docstockoutbranch' => 'dtmLastUpdated',
        'dms_inv_docstockoutbranchitem' => 'dtmLastUpdated',
        'dms_inv_docstockoutdistribution' => 'dtmLastUpdated',
        'dms_inv_docstockoutdistributionitem' => 'dtmLastUpdated',
        'dms_inv_docstockoutdistributionpr' => 'dtmLastUpdated',
        'dms_inv_docstockoutdistributionpritem' => 'dtmLastUpdated',
        'dms_inv_docstockoutsupplier' => 'dtmLastUpdated',
        'dms_inv_docstockoutsupplieritem' => 'dtmLastUpdated',
        'dms_pi_employeedistribution' => 'dtmLastUpdated',
        'dms_sd_calendarbranch' => 'dtmLastUpdated',
        'dms_sd_docdo' => 'dtmLastUpdated',
        'dms_sd_docdocorrection' => 'dtmLastUpdated',
        'dms_sd_docdocorrectionitem' => 'dtmLastUpdated',
        'dms_sd_docdoinvoice' => 'dtmLastUpdated',
        'dms_sd_docdoitem' => 'dtmLastUpdated',
        'dms_sd_docdoitemprice' => 'dtmLastUpdated',
        'dms_sd_docdoitempromo' => 'dtmLastUpdated',
        'dms_sd_docdoitemreason' => 'dtmLastUpdated',
    ],
    'skip_tables' => [],
    'limit' => 5000,
];
